Repository aoijs/documentation, pull requests merged in 2021-12, with the labels that each got.

#86 Updated usdfooter.md to v5
  src/functions/usdfooter.md
Labels: Accepted, Pending

#84 Updated usdtitle.md to v5
  src/functions/usdtitle.md
Labels: Accepted, Pending

#88 Update usdban.md
  src/functions/usdban.md
Labels: Pending

#85 Updated usddescription.md to v5
  src/functions/usddescription.md
Labels: Accepted, Pending

#89 Update usdcreaterole.md
  src/functions/usdcreaterole.md
Labels: Pending

#79 Updated $author to v5
  src/functions/usdauthor.md
Labels: Accepted, Pending

#78 Updated $addtimestamp to v5
  src/functions/usdaddtimestamp.md
Labels: Accepted, Pending

#77 Updated $sendDM to v5
  src/functions/usdsenddm.md
Labels: Accepted, Pending

#101 Update usdhasanyperms.md
  src/functions/usdhasanyperm.md
Labels: Accepted

#100 Update usdgiveroles.md
  src/functions/usdgiveroles.md
Labels: Accepted
