Repository aoijs/documentation, pull requests merged in 2022-07, with the labels that each got.

#136 Updating functions, fixing typos~
  src/SUMMARY.md
  src/functions/usdaddmessagereactions.md
  src/functions/usdaddobjectproperty.md
  src/functions/usdautocompleterespond.md
  src/functions/usdban.md
  src/functions/usdisautocomplete.md
Labels: documentation, Accepted

#141 Adding/Updating Functions
  .github/contributing-example.md
  src/SUMMARY.md
  src/functions/usdallchannelscount.md
  src/functions/usdallemojicount.md
  src/functions/usdarrayat.md
  src/functions/usdarrayconcat.md
  src/functions/usdarrayevery.md
  src/functions/usdarrayfilter.md
  src/functions/usdarrayfind.md
  src/functions/usdchannelcount.md
  src/functions/usdcreateserverinvite.md
  src/functions/usddefaultmessagenotifications.md
  src/functions/usddeletechannelvar.md
  src/functions/usddeleteglobaluservar.md
  src/functions/usddeletemessagevar.md
  src/functions/usddeleteservervar.md
  src/functions/usddeleteuservar.md
  src/functions/usddeletevar.md
  src/functions/usddisablementions.md
  src/functions/usddisablementiontype.md
  src/functions/usdgetcustomstatus.md
  src/functions/usdgetserverinvite.md
  src/functions/usdisdeafen.md
  src/functions/usdisdefeaned.md
  src/functions/usdmemberjoineddate.md
  src/functions/usdmessagepublish.md
  src/functions/usdmfalevel.md
  src/functions/usdmodifychannelperms.md
  src/functions/usdmodifyroleperms.md
  src/functions/usdmovesong.md
  src/functions/usdpausesong.md
  src/functions/usdprunemusic.md
  src/functions/usdprunestatus.md
  src/functions/usdqueuestatus.md
  src/functions/usdreply.md
  src/functions/usdresetvar.md
  src/functions/usdservermfalevel.md
  src/functions/usdsetbotname.md
  src/functions/usdsetbotusername.md
  src/functions/usdsonginfo.md
  src/functions/usduserrolecount.md
  src/functions/usdvcsize.md
  src/guides/using-callbacks.md
  src/message-formatters/README.md
  src/message-formatters/errorobjects.md
  src/message-formatters/parsers.md
Labels: documentation, enhancement, under-review

#144 Update usdawaitcomponentsuntil.md
  src/functions/usdawaitcomponentsuntil.md
Labels: documentation, enhancement, ready-for-review
